import type { LogoDocument } from "./types";
import { starPointsToPath } from "./svg";

export const sampleDocument: LogoDocument = {
  id: "sample-logo-document",
  name: "Sample Logo",
  version: 1,
  settings: {
    width: 512,
    height: 512,
    gridSize: 8,
    snapToGrid: true,
    background: "#ffffff",
  },
  layers: [
    {
      id: "sample-background",
      type: "rect",
      name: "Badge",
      visible: true,
      locked: false,
      x: 96,
      y: 112,
      width: 320,
      height: 240,
      rotation: 0,
      opacity: 1,
      fill: "#f4f7fb",
      stroke: "#14213d",
      strokeWidth: 8,
      cornerRadius: 32,
    },
    {
      id: "sample-orb",
      type: "ellipse",
      name: "Orb",
      visible: true,
      locked: false,
      x: 172,
      y: 72,
      width: 168,
      height: 168,
      rotation: 0,
      opacity: 0.95,
      fill: "#ffb703",
      stroke: "#14213d",
      strokeWidth: 8,
    },
    {
      id: "sample-star",
      type: "path",
      name: "Spark",
      visible: true,
      locked: false,
      x: 198,
      y: 120,
      width: 112,
      height: 112,
      rotation: 12,
      opacity: 1,
      fill: "#2ec4b6",
      stroke: "#14213d",
      strokeWidth: 6,
      path: starPointsToPath(256, 178, 58, 26, 5),
    },
    {
      id: "sample-wordmark",
      type: "text",
      name: "Wordmark",
      visible: true,
      locked: false,
      x: 136,
      y: 284,
      width: 240,
      height: 72,
      rotation: 0,
      opacity: 1,
      fill: "#14213d",
      stroke: "transparent",
      strokeWidth: 0,
      text: "NOVA",
      fontFamily: "Inter",
      fontSize: 56,
      fontWeight: 800,
    },
  ],
  selectedLayerIds: ["sample-wordmark"],
};
